/**
 * Desktop shell fallback theme tokens for the shared webview UI.
 *
 * Both VSCode plugin and desktop app render the same webview bundle.
 * VSCode injects its own --vscode-* CSS variables, while desktop must
 * provide them manually. Keep these variables in @vcoder/shared so the
 * two hosts stay visually aligned.
 */

export type DesktopThemeMode = 'light' | 'dark';
export type ThemeVariableMap = Record<`--${string}`, string>;

export const DESKTOP_COMMON_THEME_VARIABLES = {
  '--vscode-font-family': "-apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif",
  '--vscode-editor-font-family': "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
} as const satisfies ThemeVariableMap;

export const DESKTOP_DARK_THEME_VARIABLES = {
  '--vscode-badge-background': '#3d3b38',
  '--vscode-badge-foreground': '#e0ddd5',
  '--vscode-button-background': '#d97706',
  '--vscode-button-border': 'transparent',
  '--vscode-button-foreground': '#ffffff',
  '--vscode-button-hoverBackground': '#f59e0b',
  '--vscode-button-secondaryBackground': '#2e2c29',
  '--vscode-button-secondaryBorder': '#3d3b38',
  '--vscode-button-secondaryForeground': '#e0ddd5',
  '--vscode-button-secondaryHoverBackground': '#3a3835',
  '--vscode-charts-blue': '#60a5fa',
  '--vscode-charts-green': '#34d399',
  '--vscode-charts-orange': '#fb923c',
  '--vscode-charts-yellow': '#fbbf24',
  '--vscode-checkbox-background': '#2e2c29',
  '--vscode-checkbox-border': '#4a4845',
  '--vscode-checkbox-foreground': '#e0ddd5',
  '--vscode-descriptionForeground': '#9ca3af',
  '--vscode-disabledForeground': '#6b7280',
  '--vscode-dropdown-background': '#2a2825',
  '--vscode-dropdown-border': '#3d3b38',
  '--vscode-editor-background': '#1c1b18',
  '--vscode-editor-foreground': '#e5e2d9',
  '--vscode-editor-inactiveSelectionBackground': 'rgba(255, 255, 255, 0.06)',
  '--vscode-editorGroup-border': '#2e2c29',
  '--vscode-editorInfo-foreground': '#60a5fa',
  '--vscode-editorWarning-foreground': '#fbbf24',
  '--vscode-editorWidget-background': '#242220',
  '--vscode-errorForeground': '#f87171',
  '--vscode-focusBorder': '#d97706',
  '--vscode-foreground': '#e5e2d9',
  '--vscode-gitDecoration-addedResourceForeground': '#34d399',
  '--vscode-gitDecoration-deletedResourceForeground': '#f87171',
  '--vscode-gitDecoration-modifiedResourceForeground': '#fbbf24',
  '--vscode-icon-foreground': '#c8c5bc',
  '--vscode-input-activeBackground': '#2e2c29',
  '--vscode-input-background': '#242220',
  '--vscode-input-border': '#3d3b38',
  '--vscode-input-foreground': '#e5e2d9',
  '--vscode-input-hoverBackground': '#2a2825',
  '--vscode-input-placeholderForeground': '#6b7280',
  '--vscode-inputValidation-errorBackground': 'rgba(248, 113, 113, 0.12)',
  '--vscode-inputValidation-errorBorder': '#dc2626',
  '--vscode-inputValidation-errorForeground': '#f87171',
  '--vscode-inputValidation-infoBackground': 'rgba(96, 165, 250, 0.12)',
  '--vscode-inputValidation-infoBorder': '#3b82f6',
  '--vscode-inputValidation-warningBackground': 'rgba(251, 191, 36, 0.12)',
  '--vscode-inputValidation-warningBorder': '#d97706',
  '--vscode-keybindingLabel-background': 'rgba(255, 255, 255, 0.08)',
  '--vscode-keybindingLabel-border': 'rgba(255, 255, 255, 0.12)',
  '--vscode-keybindingLabel-bottomBorder': 'rgba(255, 255, 255, 0.16)',
  '--vscode-keybindingLabel-foreground': '#e5e2d9',
  '--vscode-list-activeSelectionBackground': 'rgba(217, 119, 6, 0.2)',
  '--vscode-list-activeSelectionForeground': '#e5e2d9',
  '--vscode-list-errorForeground': '#f87171',
  '--vscode-list-errorHoverBackground': 'rgba(248, 113, 113, 0.12)',
  '--vscode-list-hoverBackground': 'rgba(255, 255, 255, 0.05)',
  '--vscode-list-inactiveSelectionBackground': 'rgba(255, 255, 255, 0.04)',
  '--vscode-notifications-background': '#242220',
  '--vscode-notifications-border': '#2e2c29',
  '--vscode-notifications-foreground': '#e5e2d9',
  '--vscode-notificationsWarningIcon-foreground': '#fbbf24',
  '--vscode-overlay-background': 'rgba(0, 0, 0, 0.55)',
  '--vscode-panel-border': '#2e2c29',
  '--vscode-progressBar-background': '#d97706',
  '--vscode-scrollbarSlider-activeBackground': 'rgba(255, 255, 255, 0.25)',
  '--vscode-scrollbarSlider-background': 'rgba(255, 255, 255, 0.12)',
  '--vscode-scrollbarSlider-hoverBackground': 'rgba(255, 255, 255, 0.18)',
  '--vscode-settings-dropdownBorder': '#3d3b38',
  '--vscode-sideBar-background': '#222019',
  '--vscode-sideBar-border': '#2e2c29',
  '--vscode-sideBarSectionHeader-border': '#2e2c29',
  '--vscode-symbolIcon-classForeground': '#fb923c',
  '--vscode-symbolIcon-eventForeground': '#fb923c',
  '--vscode-symbolIcon-interfaceForeground': '#60a5fa',
  '--vscode-symbolIcon-methodForeground': '#c084fc',
  '--vscode-terminal-ansiBlue': '#60a5fa',
  '--vscode-terminal-ansiBrightYellow': '#fef08a',
  '--vscode-terminal-ansiCyan': '#34d399',
  '--vscode-terminal-ansiGreen': '#4ade80',
  '--vscode-terminal-ansiRed': '#f87171',
  '--vscode-terminal-ansiYellow': '#fbbf24',
  '--vscode-terminal-foreground': '#e5e2d9',
  '--vscode-testing-iconFailed': '#f87171',
  '--vscode-testing-iconPassed': '#4ade80',
  '--vscode-textBlockQuote-background': 'rgba(255, 255, 255, 0.04)',
  '--vscode-textBlockQuote-border': '#4a4845',
  '--vscode-textCodeBlock-background': 'rgba(0, 0, 0, 0.3)',
  '--vscode-textLink-activeForeground': '#fbbf24',
  '--vscode-textLink-foreground': '#fb923c',
  '--vscode-textPreformat-foreground': '#fbbf24',
  '--vscode-toolbar-hoverBackground': 'rgba(255, 255, 255, 0.06)',
  '--vscode-warningForeground': '#fbbf24',
  '--vscode-widget-border': '#3d3b38',
} as const satisfies ThemeVariableMap;

export const DESKTOP_LIGHT_THEME_VARIABLES = {
  '--vscode-badge-background': '#f0ece4',
  '--vscode-badge-foreground': '#1f2937',
  '--vscode-button-background': '#d97706',
  '--vscode-button-border': 'transparent',
  '--vscode-button-foreground': '#ffffff',
  '--vscode-button-hoverBackground': '#b45309',
  '--vscode-button-secondaryBackground': '#f0ece4',
  '--vscode-button-secondaryBorder': '#e5e0d5',
  '--vscode-button-secondaryForeground': '#1f2937',
  '--vscode-button-secondaryHoverBackground': '#e8e3d8',
  '--vscode-charts-blue': '#3b82f6',
  '--vscode-charts-green': '#16a34a',
  '--vscode-charts-orange': '#d97706',
  '--vscode-charts-yellow': '#ca8a04',
  '--vscode-checkbox-background': '#ffffff',
  '--vscode-checkbox-border': '#d1ccc2',
  '--vscode-checkbox-foreground': '#1f2937',
  '--vscode-descriptionForeground': '#6b7280',
  '--vscode-disabledForeground': '#9ca3af',
  '--vscode-dropdown-background': '#ffffff',
  '--vscode-dropdown-border': '#e5e0d5',
  '--vscode-editor-background': '#faf9f5',
  '--vscode-editor-foreground': '#1f2937',
  '--vscode-editor-inactiveSelectionBackground': 'rgba(0, 0, 0, 0.04)',
  '--vscode-editorGroup-border': '#ede9e0',
  '--vscode-editorInfo-foreground': '#3b82f6',
  '--vscode-editorWarning-foreground': '#d97706',
  '--vscode-editorWidget-background': '#f5f2eb',
  '--vscode-errorForeground': '#dc2626',
  '--vscode-focusBorder': '#d97706',
  '--vscode-foreground': '#1f2937',
  '--vscode-gitDecoration-addedResourceForeground': '#16a34a',
  '--vscode-gitDecoration-deletedResourceForeground': '#dc2626',
  '--vscode-gitDecoration-modifiedResourceForeground': '#d97706',
  '--vscode-icon-foreground': '#374151',
  '--vscode-input-activeBackground': '#ffffff',
  '--vscode-input-background': '#ffffff',
  '--vscode-input-border': '#e5e0d5',
  '--vscode-input-foreground': '#1f2937',
  '--vscode-input-hoverBackground': '#faf9f5',
  '--vscode-input-placeholderForeground': '#9ca3af',
  '--vscode-inputValidation-errorBackground': 'rgba(220, 38, 38, 0.08)',
  '--vscode-inputValidation-errorBorder': '#dc2626',
  '--vscode-inputValidation-errorForeground': '#dc2626',
  '--vscode-inputValidation-infoBackground': 'rgba(59, 130, 246, 0.08)',
  '--vscode-inputValidation-infoBorder': '#3b82f6',
  '--vscode-inputValidation-warningBackground': 'rgba(217, 119, 6, 0.08)',
  '--vscode-inputValidation-warningBorder': '#d97706',
  '--vscode-keybindingLabel-background': 'rgba(0, 0, 0, 0.06)',
  '--vscode-keybindingLabel-border': 'rgba(0, 0, 0, 0.1)',
  '--vscode-keybindingLabel-bottomBorder': 'rgba(0, 0, 0, 0.14)',
  '--vscode-keybindingLabel-foreground': '#1f2937',
  '--vscode-list-activeSelectionBackground': 'rgba(217, 119, 6, 0.12)',
  '--vscode-list-activeSelectionForeground': '#1f2937',
  '--vscode-list-errorForeground': '#dc2626',
  '--vscode-list-errorHoverBackground': 'rgba(220, 38, 38, 0.08)',
  '--vscode-list-hoverBackground': 'rgba(0, 0, 0, 0.04)',
  '--vscode-list-inactiveSelectionBackground': 'rgba(0, 0, 0, 0.03)',
  '--vscode-notifications-background': '#f5f2eb',
  '--vscode-notifications-border': '#ede9e0',
  '--vscode-notifications-foreground': '#1f2937',
  '--vscode-notificationsWarningIcon-foreground': '#d97706',
  '--vscode-overlay-background': 'rgba(0, 0, 0, 0.3)',
  '--vscode-panel-border': '#ede9e0',
  '--vscode-progressBar-background': '#d97706',
  '--vscode-scrollbarSlider-activeBackground': 'rgba(0, 0, 0, 0.3)',
  '--vscode-scrollbarSlider-background': 'rgba(0, 0, 0, 0.12)',
  '--vscode-scrollbarSlider-hoverBackground': 'rgba(0, 0, 0, 0.2)',
  '--vscode-settings-dropdownBorder': '#e5e0d5',
  '--vscode-sideBar-background': '#f2efe8',
  '--vscode-sideBar-border': '#ede9e0',
  '--vscode-sideBarSectionHeader-border': '#ede9e0',
  '--vscode-symbolIcon-classForeground': '#d97706',
  '--vscode-symbolIcon-eventForeground': '#d97706',
  '--vscode-symbolIcon-interfaceForeground': '#3b82f6',
  '--vscode-symbolIcon-methodForeground': '#9333ea',
  '--vscode-terminal-ansiBlue': '#3b82f6',
  '--vscode-terminal-ansiBrightYellow': '#ca8a04',
  '--vscode-terminal-ansiCyan': '#0891b2',
  '--vscode-terminal-ansiGreen': '#16a34a',
  '--vscode-terminal-ansiRed': '#dc2626',
  '--vscode-terminal-ansiYellow': '#d97706',
  '--vscode-terminal-foreground': '#1f2937',
  '--vscode-testing-iconFailed': '#dc2626',
  '--vscode-testing-iconPassed': '#16a34a',
  '--vscode-textBlockQuote-background': 'rgba(0, 0, 0, 0.04)',
  '--vscode-textBlockQuote-border': '#e5e0d5',
  '--vscode-textCodeBlock-background': 'rgba(0, 0, 0, 0.04)',
  '--vscode-textLink-activeForeground': '#b45309',
  '--vscode-textLink-foreground': '#d97706',
  '--vscode-textPreformat-foreground': '#d97706',
  '--vscode-toolbar-hoverBackground': 'rgba(0, 0, 0, 0.05)',
  '--vscode-warningForeground': '#d97706',
  '--vscode-widget-border': '#e5e0d5',
} as const satisfies ThemeVariableMap;

export const DESKTOP_THEME_VARIABLES: Record<DesktopThemeMode, ThemeVariableMap> = {
  dark: DESKTOP_DARK_THEME_VARIABLES,
  light: DESKTOP_LIGHT_THEME_VARIABLES,
};

export function getDesktopThemeVariables(mode: DesktopThemeMode): ThemeVariableMap {
  return DESKTOP_THEME_VARIABLES[mode];
}
